//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::SuperpoweredUniversalApp::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::SuperpoweredUniversalApp::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 2:
        {
            this->GainChannel0 = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
        }
        break;
    case 3:
        {
            ::Windows::UI::Xaml::Controls::Slider^ element3 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(element3))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::GainChannel1_ValueChanged);
        }
        break;
    case 4:
        {
            ::Windows::UI::Xaml::Controls::Slider^ element4 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(element4))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::Crossfader_ValueChanged);
        }
        break;
    case 5:
        {
            ::Windows::UI::Xaml::Controls::Slider^ element5 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(element5))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::FilterChannel0_ValueChanged);
        }
        break;
    case 6:
        {
            ::Windows::UI::Xaml::Controls::Slider^ element6 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(element6))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::GainChannel0_ValueChanged);
        }
        break;
    case 7:
        {
            ::Windows::UI::Xaml::Controls::Slider^ element7 = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(element7))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::FilterChannel1_ValueChanged);
        }
        break;
    case 8:
        {
            this->TempoSlider = safe_cast<::Windows::UI::Xaml::Controls::Slider^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Slider^>(this->TempoSlider))->ValueChanged += ref new ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::Controls::Primitives::RangeBaseValueChangedEventArgs^))&MainPage::Tempo_ValueChanged);
        }
        break;
    case 9:
        {
            ::Windows::UI::Xaml::Controls::Button^ element9 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element9))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::PitchLowerChannel0_Click);
        }
        break;
    case 10:
        {
            ::Windows::UI::Xaml::Controls::Button^ element10 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element10))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::PitchRaiseChannel0_Click);
        }
        break;
    case 11:
        {
            this->Roll1Channel1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll1Channel1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll1Channel1_Click);
        }
        break;
    case 12:
        {
            this->Roll2Channel1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll2Channel1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll2Channel1_Click);
        }
        break;
    case 13:
        {
            this->Roll3Channel1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll3Channel1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll3Channel1_Click);
        }
        break;
    case 14:
        {
            this->Roll4Channel1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll4Channel1))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll4Channel1_Click);
        }
        break;
    case 15:
        {
            this->GainChannel1 = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
        }
        break;
    case 16:
        {
            this->GainMaster = safe_cast<::Windows::UI::Xaml::Controls::ProgressBar^>(__target);
        }
        break;
    case 17:
        {
            this->Roll1Channel0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll1Channel0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll1Channel0_Click);
        }
        break;
    case 18:
        {
            this->Roll2Channel0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll2Channel0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll2Channel0_Click);
        }
        break;
    case 19:
        {
            this->Roll3Channel0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll3Channel0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll3Channel0_Click);
        }
        break;
    case 20:
        {
            this->Roll4Channel0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->Roll4Channel0))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Roll4Channel0_Click);
        }
        break;
    case 21:
        {
            this->PitchChannel0 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 22:
        {
            ::Windows::UI::Xaml::Controls::Button^ element22 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element22))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::PitchLowerChannel1_Click);
        }
        break;
    case 23:
        {
            this->PitchChannel1 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
        }
        break;
    case 24:
        {
            ::Windows::UI::Xaml::Controls::Button^ element24 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element24))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::PitchRaiseChannel1_Click);
        }
        break;
    case 25:
        {
            ::Windows::UI::Xaml::Controls::Button^ element25 = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::Button^>(element25))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Button_Click);
        }
        break;
    case 26:
        {
            ::Windows::UI::Xaml::Controls::TextBlock^ element26 = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(element26))->SelectionChanged += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::SuperpoweredUniversalApp::MainPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::TextBlock_SelectionChanged);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::SuperpoweredUniversalApp::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


