#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class ProgressBar;
                ref class Slider;
                ref class Button;
            }
        }
    }
}

namespace SuperpoweredUniversalApp
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        void UnloadObject(::Windows::UI::Xaml::DependencyObject^ dependencyObject);
        void DisconnectUnloadedObject(int connectionId);
    
    private:
        bool _contentLoaded;
    
        class MainPage_obj1_Bindings;
    
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ GainChannel0;
        private: ::Windows::UI::Xaml::Controls::Slider^ TempoSlider;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll1Channel1;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll2Channel1;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll3Channel1;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll4Channel1;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ GainChannel1;
        private: ::Windows::UI::Xaml::Controls::ProgressBar^ GainMaster;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll1Channel0;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll2Channel0;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll3Channel0;
        private: ::Windows::UI::Xaml::Controls::Button^ Roll4Channel0;
        private: ::Windows::UI::Xaml::Controls::Button^ PitchChannel0;
        private: ::Windows::UI::Xaml::Controls::Button^ PitchChannel1;
    };
}

